import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(description="Plot fine-tuning metrics from a Trainer metrics CSV.")
    parser.add_argument(
        "--metrics-path",
        default="./results/logs/training_metrics.csv",
        help="Path to the metrics CSV generated by scripts/finetune.py",
    )
    parser.add_argument(
        "--output-dir",
        default="./results/metrics_plots",
        help="Directory where metric plots will be written.",
    )
    parser.add_argument("--dpi", type=int, default=200, help="Image DPI for saved figures.")
    return parser.parse_args()


def _pick_x_axis(metric_df):
    if "step" in metric_df.columns and metric_df["step"].notna().any():
        return "step"
    if "epoch" in metric_df.columns and metric_df["epoch"].notna().any():
        return "epoch"
    return None


def _plot_metric(metric_df, metric_name, title, output_file, dpi):
    plot_df = metric_df[[metric_name] + [col for col in ["step", "epoch"] if col in metric_df.columns]].copy()
    plot_df[metric_name] = pd.to_numeric(plot_df[metric_name], errors="coerce")
    plot_df = plot_df.dropna(subset=[metric_name])

    if plot_df.empty:
        return False

    x_axis = _pick_x_axis(plot_df)
    if x_axis is None:
        plot_df = plot_df.reset_index(drop=True)
        x_data = plot_df.index
        x_label = "index"
    else:
        plot_df[x_axis] = pd.to_numeric(plot_df[x_axis], errors="coerce")
        plot_df = plot_df.dropna(subset=[x_axis])
        if plot_df.empty:
            return False
        x_data = plot_df[x_axis]
        x_label = x_axis

    plt.figure(figsize=(10, 5))
    plt.plot(x_data, plot_df[metric_name], linewidth=2)
    plt.title(title)
    plt.xlabel(x_label)
    plt.ylabel(metric_name)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_file, dpi=dpi)
    plt.close()
    return True


def main():
    args = parse_args()

    metrics_path = Path(args.metrics_path)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not metrics_path.exists():
        raise FileNotFoundError(f"Metrics file not found: {metrics_path}")

    metrics_df = pd.read_csv(metrics_path)

    metric_specs = [
        ("loss", "Training Loss", output_dir / "training_loss.png"),
        ("eval_loss", "Validation Loss", output_dir / "validation_loss.png"),
        ("learning_rate", "Learning Rate", output_dir / "learning_rate.png"),
        ("grad_norm", "Gradient Norm", output_dir / "gradient_norm.png"),
    ]

    saved_files = []
    skipped_metrics = []

    for metric_name, title, output_file in metric_specs:
        if metric_name not in metrics_df.columns:
            skipped_metrics.append(metric_name)
            continue

        saved = _plot_metric(metrics_df, metric_name, title, output_file, args.dpi)
        if saved:
            saved_files.append(str(output_file))
        else:
            skipped_metrics.append(metric_name)

    print(f"Rows loaded: {len(metrics_df)}")
    print(f"Saved plots: {len(saved_files)}")
    for file_path in saved_files:
        print(f"  - {file_path}")

    if skipped_metrics:
        print("Skipped metrics (missing or empty): " + ", ".join(skipped_metrics))


if __name__ == "__main__":
    main()
